# Generated by Django 5.0.3 on 2024-09-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_formularios_codigo_alter_formularios_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularios',
            name='codigo',
            field=models.CharField(default='dfs', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formularios',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formularios',
            name='nome',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formularios',
            name='telefone',
            field=models.CharField(default='6546765489674', max_length=14),
            preserve_default=False,
        ),
    ]
